import fs from 'fs';
import path from 'path';
import { Event, Promotion, Organization, User, Notification } from './types';

const DB_PATH = path.join(process.cwd(), 'data', 'db.json');

export interface DBStructure {
  events: Event[];
  promotions: Promotion[];
  organizations: Organization[];
  users: User[];
  notifications: Notification[];
}

const initialOrganizations: Organization[] = [
  {
    id: 'org-sg',
    name: 'Student Government Association',
    description: 'Advocating for student voices, allocating funding for student events, and governing campus regulations.',
    verified: true,
    members: ['Alex Rivera', 'David Kim'],
    logoColor: 'indigo',
    views: 145,
    saves: 32,
    rsvps: 98
  },
  {
    id: 'org-isa',
    name: 'International Student Association',
    description: 'Fostering a global community and organizing cultural exchange events on campus.',
    verified: true,
    members: ['Michael Chen', 'Sarah Jenkins'],
    logoColor: 'sky',
    views: 89,
    saves: 12,
    rsvps: 45
  },
  {
    id: 'org-stem',
    name: 'STEM Club',
    description: 'A coalition of science, math, and engineering students hosting build workshops and guest tech lectures.',
    verified: true,
    members: ['Sarah Jenkins', 'Alex Rivera'],
    logoColor: 'emerald',
    views: 242,
    saves: 78,
    rsvps: 180
  },
  {
    id: 'org-cab',
    name: 'Campus Activities Board',
    description: 'Planning homecoming, concerts, campus traditions, and Friday night events.',
    verified: true,
    members: ['Michael Chen', 'David Kim'],
    logoColor: 'violet',
    views: 452,
    saves: 110,
    rsvps: 340
  },
  {
    id: 'org-athletics',
    name: 'Blue Bears Athletics',
    description: 'Supporting varsity sports, competitive athletics, and student fitness.',
    verified: true,
    members: ['Michael Chen'],
    logoColor: 'amber',
    views: 310,
    saves: 56,
    rsvps: 220
  },
  {
    id: 'org-bsu',
    name: 'Black Student Union',
    description: 'Empowering Black students, promoting academic excellence, and hosting cultural showcases.',
    verified: true,
    members: ['Alex Rivera'],
    logoColor: 'rose',
    views: 189,
    saves: 43,
    rsvps: 112
  },
  {
    id: 'org-cdc',
    name: 'Career Development Center',
    description: 'Providing resume workshops, career counseling, and hosting employer recruitment events.',
    verified: true,
    members: ['Sarah Jenkins'],
    logoColor: 'cream',
    views: 120,
    saves: 18,
    rsvps: 60
  }
];

const initialUsers: User[] = [
  {
    username: 'michael_c',
    name: 'Michael Chen',
    role: 'student',
    organizations: ['org-isa', 'org-cab', 'org-athletics'],
    major: 'Computer Science',
    gradYear: '2028',
    school: 'School of Engineering',
    avatar: 'MC'
  },
  {
    username: 'sarah_j',
    name: 'Sarah Jenkins',
    role: 'student_leader',
    organizations: ['org-stem', 'org-isa', 'org-athletics'],
    major: 'Mechanical Engineering',
    gradYear: '2027',
    school: 'School of Engineering',
    avatar: 'SJ'
  },
  {
    username: 'alex_r',
    name: 'Alex Rivera',
    role: 'student_leader',
    organizations: ['org-sg', 'org-stem', 'org-bsu'],
    major: 'Political Science',
    gradYear: '2026',
    school: 'School of Public Affairs',
    avatar: 'AR'
  },
  {
    username: 'admin_dean',
    name: 'Dean Dean',
    role: 'admin',
    organizations: [],
    major: 'Higher Ed Administration',
    gradYear: 'N/A',
    school: 'Student Affairs Division',
    avatar: 'DD'
  }
];

const initialEvents: Event[] = [
  {
    id: 'evt-hc-kickoff',
    title: 'Homecoming Kickoff Rally',
    description: 'Ignite school spirit and launch the homecoming season with full-force energy! Highlighting live student DJs, food trucks, pep rally drums, and official giveaways. Dress in our school colors!',
    category: 'Social',
    ownershipType: 'school',
    complexityType: 'complex',
    status: 'approved',
    date: '2026-10-09',
    time: '18:00',
    endTime: '21:00',
    location: 'Main University Plaza',
    locationType: 'outdoor',
    attendees: ['Michael Chen', 'Sarah Jenkins', 'Alex Rivera'],
    interested: [],
    savedBy: ['Michael Chen', 'Alex Rivera'],
    organizer: 'Campus Activities Board',
    organizationId: 'org-cab',
    organizationName: 'Campus Activities Board',
    featured: true,
    views: 890,
    estimatedAttendance: 600,
    fundingRequested: false,
    transportationNeeded: false,
    coverImage: '/pexels-hanna-elesha-abraham-1587801282-27498756.jpg',
    free: true,
    capacity: 1000,
    visibility: 'public'
  },
  {
    id: 'evt-career-night',
    title: 'Career Fair Networking Night',
    description: 'Establish crucial connections for summer internships and entry-level positions. Interact with recruiters from top engineering, consulting, and creative agencies. Resume printouts required.',
    category: 'Career',
    ownershipType: 'school',
    complexityType: 'complex',
    status: 'approved',
    date: '2026-07-15',
    time: '17:00',
    endTime: '20:30',
    location: 'Grand Student Ballroom',
    locationType: 'indoor',
    attendees: ['Sarah Jenkins', 'Alex Rivera'],
    interested: ['Michael Chen'],
    savedBy: ['Sarah Jenkins'],
    organizer: 'Career Development Center',
    organizationId: 'org-cdc',
    organizationName: 'Career Development Center',
    featured: true,
    views: 450,
    estimatedAttendance: 350,
    fundingRequested: false,
    transportationNeeded: false,
    coverImage: '/pexels-rdne-7648057.jpg',
    free: true,
    capacity: 400,
    visibility: 'public'
  },
  {
    id: 'evt-intl-mixer',
    title: 'International Student Mixer',
    description: 'Welcome and integrate international students into campus life. Enjoy speed-networking icebreakers, sample foods from different continents, and find your local support networks.',
    category: 'Social',
    ownershipType: 'organization',
    complexityType: 'standard',
    status: 'approved',
    date: '2026-07-08',
    time: '16:00',
    endTime: '18:00',
    location: 'Student Union Terrace',
    locationType: 'outdoor',
    attendees: ['Michael Chen', 'Sarah Jenkins'],
    interested: ['Alex Rivera'],
    savedBy: ['Michael Chen'],
    organizer: 'Michael Chen',
    organizationId: 'org-isa',
    organizationName: 'International Student Association',
    featured: false,
    views: 210,
    estimatedAttendance: 100,
    fundingRequested: true,
    transportationNeeded: false,
    coverImage: '/pexels-yaroslav-shuraev-8513385.jpg',
    free: true,
    capacity: 120,
    visibility: 'public'
  },
  {
    id: 'evt-basketball',
    title: 'Blue Bears Season Opener',
    description: 'Witness the Blue Bears battle their arch-rivals in the first match of the college basketball tournament. Free foam fingers for the first 100 students!',
    category: 'Sports',
    ownershipType: 'school',
    complexityType: 'standard',
    status: 'approved',
    date: '2026-07-12',
    time: '19:30',
    endTime: '22:00',
    location: 'Alumni Arena',
    locationType: 'indoor',
    attendees: ['Michael Chen'],
    interested: ['Sarah Jenkins', 'Alex Rivera'],
    savedBy: ['Michael Chen', 'Sarah Jenkins'],
    organizer: 'Blue Bears Athletics',
    organizationId: 'org-athletics',
    organizationName: 'Blue Bears Athletics',
    featured: false,
    views: 520,
    estimatedAttendance: 800,
    fundingRequested: false,
    transportationNeeded: false,
    coverImage: '/pexels-caleboquendo-34598092.jpg',
    free: true,
    capacity: 1200,
    visibility: 'public'
  },
  {
    id: 'evt-greek-show',
    title: 'Greek Yard Show',
    description: 'The step performance tradition returns! Watch campus fraternities and sororities showcase complex stepping, high-energy dancing, and chapter chants.',
    category: 'Culture',
    ownershipType: 'organization',
    complexityType: 'complex',
    status: 'approved',
    date: '2026-08-04',
    time: '18:00',
    endTime: '21:00',
    location: 'Amphitheater',
    locationType: 'outdoor',
    attendees: ['Alex Rivera', 'Michael Chen'],
    interested: ['Sarah Jenkins'],
    savedBy: ['Alex Rivera'],
    organizer: 'Alex Rivera',
    organizationId: 'org-sg',
    organizationName: 'Student Government Association',
    featured: false,
    views: 380,
    estimatedAttendance: 250,
    fundingRequested: true,
    transportationNeeded: false,
    coverImage: '/pexels-amine-1285347-9371719.jpg',
    free: true,
    capacity: 400,
    visibility: 'public'
  },
  {
    id: 'evt-stem-expo',
    title: 'STEM Innovation Expo',
    description: 'Explore research projects, hardware builds, and custom coding prototypes developed by students. Network with judges from tech companies and see live 3D printing.',
    category: 'Academic',
    ownershipType: 'organization',
    complexityType: 'standard',
    status: 'approved',
    date: '2026-07-22',
    time: '13:00',
    endTime: '17:00',
    location: 'Engineering Science Center',
    locationType: 'indoor',
    attendees: ['Sarah Jenkins', 'Alex Rivera'],
    interested: ['Michael Chen'],
    savedBy: ['Sarah Jenkins'],
    organizer: 'Sarah Jenkins',
    organizationId: 'org-stem',
    organizationName: 'STEM Club',
    featured: false,
    views: 180,
    estimatedAttendance: 80,
    fundingRequested: false,
    transportationNeeded: false,
    coverImage: '/pexels-hassan-zafar-949411593-29927473.jpg',
    free: true,
    capacity: 150,
    visibility: 'public'
  },
  {
    id: 'evt-sg-townhall',
    title: 'Student Government Town Hall',
    description: 'Speak directly with your student body representatives. Voice opinions on housing services, cafeteria hours, and allocations of student organization budgets.',
    category: 'Academic',
    ownershipType: 'organization',
    complexityType: 'quick',
    status: 'approved',
    date: '2026-07-06',
    time: '15:00',
    endTime: '16:00',
    location: 'Multipurpose Room B',
    locationType: 'indoor',
    attendees: ['Alex Rivera'],
    interested: ['Michael Chen', 'Sarah Jenkins'],
    savedBy: [],
    organizer: 'Alex Rivera',
    organizationId: 'org-sg',
    organizationName: 'Student Government Association',
    featured: false,
    views: 95,
    estimatedAttendance: 30,
    fundingRequested: false,
    transportationNeeded: false,
    coverImage: '/pexels-nick-rush-2508183-11211233.jpg',
    free: true,
    capacity: 50,
    visibility: 'public'
  },
  {
    id: 'evt-wellness-ws',
    title: 'Wellness & Mental Health Workshop',
    description: 'Decompress from classes with mindfulness exercises, meditation guides, and complimentary yoga. Take home wellness kits and healthy snacks.',
    category: 'Social',
    ownershipType: 'school',
    complexityType: 'quick',
    status: 'approved',
    date: '2026-07-09',
    time: '14:00',
    endTime: '15:30',
    location: 'Campus Gardens',
    locationType: 'outdoor',
    attendees: ['Sarah Jenkins', 'Michael Chen'],
    interested: [],
    savedBy: ['Sarah Jenkins'],
    organizer: 'Student Affairs',
    featured: false,
    views: 110,
    estimatedAttendance: 25,
    fundingRequested: false,
    transportationNeeded: false,
    coverImage: '/pexels-tima-miroshnichenko-5439368.jpg',
    free: true,
    capacity: 30,
    visibility: 'public'
  },
  {
    id: 'evt-cultural-night',
    title: 'BSA Cultural Gala Night',
    description: 'Celebrate legacy and heritage with music, performance poetry, history displays, and fashion. A signature annual celebration for student groups.',
    category: 'Culture',
    ownershipType: 'organization',
    complexityType: 'standard',
    status: 'pending',
    date: '2026-07-18',
    time: '19:00',
    endTime: '22:00',
    location: 'Student Union Ballroom',
    locationType: 'indoor',
    attendees: [],
    interested: ['Alex Rivera', 'Michael Chen'],
    savedBy: [],
    organizer: 'Alex Rivera',
    organizationId: 'org-bsu',
    organizationName: 'Black Student Union',
    featured: false,
    views: 45,
    estimatedAttendance: 120,
    fundingRequested: true,
    transportationNeeded: false,
    coverImage: '/pexels-cottonbro-5989925.jpg',
    free: true,
    capacity: 200,
    visibility: 'public'
  },
  {
    id: 'evt-kickback',
    title: 'Friday Night Kickback',
    description: 'Wind down after midterms with board games, free pizza, game consoles, and casual conversations in a low-stakes environment.',
    category: 'Social',
    ownershipType: 'organization',
    complexityType: 'quick',
    status: 'pending',
    date: '2026-07-10',
    time: '20:00',
    endTime: '23:00',
    location: 'CAB Lounge',
    locationType: 'indoor',
    attendees: [],
    interested: ['Michael Chen'],
    savedBy: [],
    organizer: 'Michael Chen',
    organizationId: 'org-cab',
    organizationName: 'Campus Activities Board',
    featured: false,
    views: 32,
    estimatedAttendance: 15,
    fundingRequested: false,
    transportationNeeded: false,
    coverImage: '/pexels-amar-20025867.jpg',
    free: true,
    capacity: 25,
    visibility: 'public'
  },
  {
    id: 'mock-sports-1',
    title: 'Blue Bears Basketball Game',
    description: 'Come support the Blue Bears in our season opening basketball game! Free entry for all students with school ID.',
    category: 'Sports',
    ownershipType: 'school',
    complexityType: 'standard',
    status: 'approved',
    date: '2026-10-12',
    time: '19:00',
    location: 'Campus Arena',
    locationType: 'indoor',
    attendees: [],
    interested: [],
    savedBy: [],
    organizer: 'Blue Bears Athletics',
    organizationName: 'Blue Bears Athletics',
    coverImage: '/pexels-marwen-larafa-2159807713-37714941.jpg',
    free: true,
    capacity: 2000,
    featured: false,
    views: 120,
    visibility: 'public',
    estimatedAttendance: 100
  },
  {
    id: 'mock-sports-2',
    title: 'Varsity Tennis Match',
    description: 'Our varsity tennis team takes on the state champions. Refreshments will be served.',
    category: 'Sports',
    ownershipType: 'school',
    complexityType: 'quick',
    status: 'approved',
    date: '2026-10-18',
    time: '15:00',
    location: 'Tennis Courts',
    locationType: 'outdoor',
    attendees: [],
    interested: [],
    savedBy: [],
    organizer: 'Blue Bears Athletics',
    organizationName: 'Blue Bears Athletics',
    coverImage: '/pexels-hanna-elesha-abraham-1587801282-27498756.jpg',
    free: true,
    capacity: 100,
    featured: false,
    views: 45,
    visibility: 'public',
    estimatedAttendance: 100
  },
  {
    id: 'mock-sports-3',
    title: 'Intramural Soccer Finals',
    description: 'The final game of the intramural soccer tournament. Who will take home the trophy?',
    category: 'Sports',
    ownershipType: 'organization',
    complexityType: 'quick',
    status: 'approved',
    date: '2026-10-24',
    time: '17:00',
    location: 'Athletic Field',
    locationType: 'outdoor',
    attendees: [],
    interested: [],
    savedBy: [],
    organizer: 'Student Government Association',
    organizationName: 'Student Government Association',
    coverImage: '/pexels-yaroslav-shuraev-8513385.jpg',
    free: true,
    capacity: 300,
    featured: false,
    views: 75,
    visibility: 'public',
    estimatedAttendance: 100
  },
  {
    id: 'mock-home-1',
    title: 'Homecoming Football Game',
    description: 'The biggest game of the year! Join thousands of alumni and students for the annual Homecoming Football Game.',
    category: 'Homecoming',
    ownershipType: 'school',
    complexityType: 'complex',
    status: 'approved',
    date: '2026-10-15',
    time: '14:00',
    location: 'Memorial Stadium',
    locationType: 'outdoor',
    attendees: [],
    interested: [],
    savedBy: [],
    organizer: 'Campus Activities Board',
    organizationName: 'Campus Activities Board',
    coverImage: '/pexels-marwen-larafa-2159807713-37714941.jpg',
    free: true,
    capacity: 5000,
    featured: false,
    views: 310,
    visibility: 'public',
    estimatedAttendance: 100
  },
  {
    id: 'mock-home-2',
    title: 'Homecoming Concert & Dance',
    description: 'Celebrate Homecoming with a live concert featuring guest student DJs and local bands.',
    category: 'Homecoming',
    ownershipType: 'school',
    complexityType: 'complex',
    status: 'approved',
    date: '2026-10-16',
    time: '20:00',
    location: 'Main Plaza',
    locationType: 'outdoor',
    attendees: [],
    interested: [],
    savedBy: [],
    organizer: 'Campus Activities Board',
    organizationName: 'Campus Activities Board',
    coverImage: '/pexels-franco-monsalvo-252430633-37980178.jpg',
    free: true,
    capacity: 1500,
    featured: false,
    views: 450,
    visibility: 'public',
    estimatedAttendance: 100
  },
  {
    id: 'mock-home-3',
    title: 'Alumni Tailgate Party',
    description: 'Connect with alumni, enjoy free food and drinks, and get ready for the game.',
    category: 'Homecoming',
    ownershipType: 'school',
    complexityType: 'standard',
    status: 'approved',
    date: '2026-10-15',
    time: '11:00',
    location: 'West Lot',
    locationType: 'outdoor',
    attendees: [],
    interested: [],
    savedBy: [],
    organizer: 'Campus Activities Board',
    organizationName: 'Campus Activities Board',
    coverImage: '/pexels-gu-ko-2150570603-31827067.jpg',
    free: true,
    capacity: 500,
    featured: false,
    views: 180,
    visibility: 'public',
    estimatedAttendance: 100
  },
  {
    id: 'mock-career-1',
    title: 'Annual Fall Career Fair',
    description: 'Meet recruiters from over 100 companies hiring for internships and full-time jobs.',
    category: 'Career Fair',
    ownershipType: 'school',
    complexityType: 'complex',
    status: 'approved',
    date: '2026-10-20',
    time: '10:00',
    location: 'Student Union Ballroom',
    locationType: 'indoor',
    attendees: [],
    interested: [],
    savedBy: [],
    organizer: 'Career Development Center',
    organizationName: 'Career Development Center',
    coverImage: '/pexels-edward-jenner-4031319.jpg',
    free: true,
    capacity: 1000,
    featured: false,
    views: 245,
    visibility: 'public',
    estimatedAttendance: 100
  },
  {
    id: 'mock-career-2',
    title: 'Tech Resume Review',
    description: 'Get your resume reviewed by senior engineers and hiring managers before the career fair.',
    category: 'Career Fair',
    ownershipType: 'school',
    complexityType: 'standard',
    status: 'approved',
    date: '2026-10-21',
    time: '14:00',
    location: 'Science Hall 101',
    locationType: 'indoor',
    attendees: [],
    interested: [],
    savedBy: [],
    organizer: 'Career Development Center',
    organizationName: 'Career Development Center',
    coverImage: '/pexels-markus-winkler-1430818-12199407.jpg',
    free: true,
    capacity: 200,
    featured: false,
    views: 89,
    visibility: 'public',
    estimatedAttendance: 100
  },
  {
    id: 'mock-career-3',
    title: 'Mock Interview Blitz',
    description: 'Practice your interview skills with real-time feedback in this fast-paced mock interview event.',
    category: 'Career Fair',
    ownershipType: 'school',
    complexityType: 'standard',
    status: 'approved',
    date: '2026-10-22',
    time: '13:00',
    location: 'Career Center',
    locationType: 'indoor',
    attendees: [],
    interested: [],
    savedBy: [],
    organizer: 'Career Development Center',
    organizationName: 'Career Development Center',
    coverImage: '/pexels-cottonbro-5989925.jpg',
    free: true,
    capacity: 150,
    featured: false,
    views: 70,
    visibility: 'public',
    estimatedAttendance: 100
  },
  {
    id: 'mock-work-1',
    title: 'STEM Club Code & Coffee',
    description: 'Bring your laptop, grab a cup of coffee, and work on your coding projects with fellow STEM students.',
    category: 'Workshops',
    ownershipType: 'organization',
    complexityType: 'quick',
    status: 'approved',
    date: '2026-10-10',
    time: '09:00',
    location: 'Engineering Lab B',
    locationType: 'indoor',
    attendees: [],
    interested: [],
    savedBy: [],
    organizer: 'STEM Club',
    organizationName: 'STEM Club',
    coverImage: '/pexels-tima-miroshnichenko-5439368.jpg',
    free: true,
    capacity: 40,
    featured: false,
    views: 95,
    visibility: 'public',
    estimatedAttendance: 100
  },
  {
    id: 'mock-work-2',
    title: 'Creative Writing Workshop',
    description: 'Unleash your creativity. Participate in writing prompts, share your work, and get constructive feedback.',
    category: 'Workshops',
    ownershipType: 'organization',
    complexityType: 'quick',
    status: 'approved',
    date: '2026-10-14',
    time: '16:00',
    location: 'Library Room 302',
    locationType: 'indoor',
    attendees: [],
    interested: [],
    savedBy: [],
    organizer: 'International Student Association',
    organizationName: 'International Student Association',
    coverImage: '/pexels-cottonbro-5989925.jpg',
    free: true,
    capacity: 25,
    featured: false,
    views: 34,
    visibility: 'public',
    estimatedAttendance: 100
  },
  {
    id: 'mock-work-3',
    title: 'UI/UX Design Masterclass',
    description: 'Learn the principles of modern interface design. Perfect for aspiring product designers and developers.',
    category: 'Workshops',
    ownershipType: 'organization',
    complexityType: 'standard',
    status: 'approved',
    date: '2026-10-19',
    time: '18:00',
    location: 'Design Studio',
    locationType: 'indoor',
    attendees: [],
    interested: [],
    savedBy: [],
    organizer: 'STEM Club',
    organizationName: 'STEM Club',
    coverImage: '/pexels-markus-winkler-1430818-12199407.jpg',
    free: true,
    capacity: 60,
    featured: false,
    views: 110,
    visibility: 'public',
    estimatedAttendance: 100
  },
  {
    id: 'mock-ori-1',
    title: 'Freshman Welcome Rally',
    description: 'Welcome to campus! Meet your class, learn about campus traditions, and kick off your college journey.',
    category: 'Orientation',
    ownershipType: 'school',
    complexityType: 'complex',
    status: 'approved',
    date: '2026-10-01',
    time: '09:00',
    location: 'Quad',
    locationType: 'outdoor',
    attendees: [],
    interested: [],
    savedBy: [],
    organizer: 'Student Government Association',
    organizationName: 'Student Government Association',
    coverImage: '/pexels-ron-lach-8576102.jpg',
    free: true,
    capacity: 2000,
    featured: false,
    views: 520,
    visibility: 'public',
    estimatedAttendance: 100
  },
  {
    id: 'mock-ori-2',
    title: 'Campus Scavenger Hunt',
    description: 'Explore the campus, solve clues, and win prizes with your orientation group.',
    category: 'Orientation',
    ownershipType: 'school',
    complexityType: 'standard',
    status: 'approved',
    date: '2026-10-02',
    time: '14:00',
    location: 'Student Center',
    locationType: 'outdoor',
    attendees: [],
    interested: [],
    savedBy: [],
    organizer: 'Student Government Association',
    organizationName: 'Student Government Association',
    coverImage: '/pexels-gu-ko-2150570603-31827067.jpg',
    free: true,
    capacity: 500,
    featured: false,
    views: 180,
    visibility: 'public',
    estimatedAttendance: 100
  },
  {
    id: 'mock-ori-3',
    title: "President's Ice Cream Social",
    description: 'Enjoy free ice cream and mingle with the university president, faculty, and staff.',
    category: 'Orientation',
    ownershipType: 'school',
    complexityType: 'quick',
    status: 'approved',
    date: '2026-10-03',
    time: '16:00',
    location: "President's Lawn",
    locationType: 'outdoor',
    attendees: [],
    interested: [],
    savedBy: [],
    organizer: 'Student Government Association',
    organizationName: 'Student Government Association',
    coverImage: '/pexels-yaroslav-shuraev-8513385.jpg',
    free: true,
    capacity: 800,
    featured: false,
    views: 340,
    visibility: 'public',
    estimatedAttendance: 100
  },
  {
    id: 'mock-concert-1',
    title: 'Acoustic Sunset Session',
    description: 'Relax to live acoustic music as the sun sets. Featuring talented student singer-songwriters.',
    category: 'Concerts',
    ownershipType: 'organization',
    complexityType: 'quick',
    status: 'approved',
    date: '2026-10-09',
    time: '18:00',
    location: 'Amphitheater',
    locationType: 'outdoor',
    attendees: [],
    interested: [],
    savedBy: [],
    organizer: 'Campus Activities Board',
    organizationName: 'Campus Activities Board',
    coverImage: '/pexels-amine-1285347-9371719.jpg',
    free: true,
    capacity: 300,
    featured: false,
    views: 145,
    visibility: 'public',
    estimatedAttendance: 100
  },
  {
    id: 'mock-concert-2',
    title: 'Battle of the Bands',
    description: 'Campus bands face off for a grand prize and the chance to open the spring music festival.',
    category: 'Concerts',
    ownershipType: 'organization',
    complexityType: 'standard',
    status: 'approved',
    date: '2026-10-23',
    time: '20:00',
    location: 'Campus Theatre',
    locationType: 'indoor',
    attendees: [],
    interested: [],
    savedBy: [],
    organizer: 'Campus Activities Board',
    organizationName: 'Campus Activities Board',
    coverImage: '/pexels-franco-monsalvo-252430633-37980178.jpg',
    free: true,
    capacity: 500,
    featured: false,
    views: 289,
    visibility: 'public',
    estimatedAttendance: 100
  },
  {
    id: 'mock-concert-3',
    title: 'Jazz Ensemble Fall Show',
    description: 'An evening of classic and contemporary jazz performed by the university jazz ensemble.',
    category: 'Concerts',
    ownershipType: 'school',
    complexityType: 'standard',
    status: 'approved',
    date: '2026-10-30',
    time: '19:30',
    location: 'Music Hall',
    locationType: 'indoor',
    attendees: [],
    interested: [],
    savedBy: [],
    organizer: 'Campus Activities Board',
    organizationName: 'Campus Activities Board',
    coverImage: '/pexels-franco-monsalvo-252430633-37980178.jpg',
    free: true,
    capacity: 400,
    featured: false,
    views: 110,
    visibility: 'public',
    estimatedAttendance: 100
  },
  {
    id: 'mock-party-1',
    title: 'Welcome Back Neon Rave',
    description: 'Light up the night! Join us for a high-energy neon rave with laser shows and electronic music.',
    category: 'Parties',
    ownershipType: 'organization',
    complexityType: 'complex',
    status: 'approved',
    date: '2026-10-05',
    time: '21:00',
    location: 'Student Plaza',
    locationType: 'outdoor',
    attendees: [],
    interested: [],
    savedBy: [],
    organizer: 'Campus Activities Board',
    organizationName: 'Campus Activities Board',
    coverImage: '/pexels-amine-1285347-9371719.jpg',
    free: true,
    capacity: 1200,
    featured: false,
    views: 680,
    visibility: 'public',
    estimatedAttendance: 100
  },
  {
    id: 'mock-party-2',
    title: 'Halloween Costume Ball',
    description: 'Spooky season is here. Dress in your best costume and join us for dancing, treats, and contests.',
    category: 'Parties',
    ownershipType: 'organization',
    complexityType: 'standard',
    status: 'approved',
    date: '2026-10-31',
    time: '20:00',
    location: 'Gymnasium',
    locationType: 'indoor',
    attendees: [],
    interested: [],
    savedBy: [],
    organizer: 'Campus Activities Board',
    organizationName: 'Campus Activities Board',
    coverImage: '/pexels-ron-lach-8576102.jpg',
    free: true,
    capacity: 800,
    featured: false,
    views: 450,
    visibility: 'public',
    estimatedAttendance: 100
  },
  {
    id: 'mock-club-1',
    title: 'Astronomy Club Stargazing',
    description: 'View planets, star clusters, and nebulae through high-powered club telescopes.',
    category: 'Clubs',
    ownershipType: 'organization',
    complexityType: 'quick',
    status: 'approved',
    date: '2026-10-12',
    time: '21:00',
    location: 'Observatory Hill',
    locationType: 'outdoor',
    attendees: [],
    interested: [],
    savedBy: [],
    organizer: 'STEM Club',
    organizationName: 'STEM Club',
    coverImage: '/pexels-amine-1285347-9371719.jpg',
    free: true,
    capacity: 50,
    featured: false,
    views: 98,
    visibility: 'public',
    estimatedAttendance: 100
  },
  {
    id: 'mock-club-2',
    title: 'Chess Club Open Tournament',
    description: 'Test your strategy. Open to all skill levels from beginners to grandmasters.',
    category: 'Clubs',
    ownershipType: 'organization',
    complexityType: 'quick',
    status: 'approved',
    date: '2026-10-17',
    time: '13:00',
    location: 'Student Union',
    locationType: 'indoor',
    attendees: [],
    interested: [],
    savedBy: [],
    organizer: 'STEM Club',
    organizationName: 'STEM Club',
    coverImage: '/pexels-tima-miroshnichenko-5439368.jpg',
    free: true,
    capacity: 64,
    featured: false,
    views: 42,
    visibility: 'public',
    estimatedAttendance: 100
  },
  {
    id: 'mock-acad-1',
    title: 'Distinguished Lecture Series',
    description: 'An intellectual discussion featuring guest speakers exploring cutting-edge scientific innovations.',
    category: 'Academic Events',
    ownershipType: 'school',
    complexityType: 'standard',
    status: 'approved',
    date: '2026-10-08',
    time: '16:00',
    location: 'Auditorium A',
    locationType: 'indoor',
    attendees: [],
    interested: [],
    savedBy: [],
    organizer: 'STEM Club',
    organizationName: 'STEM Club',
    coverImage: '/pexels-edward-jenner-4031319.jpg',
    free: true,
    capacity: 150,
    featured: false,
    views: 120,
    visibility: 'public',
    estimatedAttendance: 100
  },
  {
    id: 'mock-acad-2',
    title: 'Undergraduate Research Symposium',
    description: 'See the impressive research posters and presentations by student researchers across all disciplines.',
    category: 'Academic Events',
    ownershipType: 'school',
    complexityType: 'standard',
    status: 'approved',
    date: '2026-10-22',
    time: '10:00',
    location: 'Science Center Lobby',
    locationType: 'indoor',
    attendees: [],
    interested: [],
    savedBy: [],
    organizer: 'STEM Club',
    organizationName: 'STEM Club',
    coverImage: '/pexels-edward-jenner-4031319.jpg',
    free: true,
    capacity: 200,
    featured: false,
    views: 160,
    visibility: 'public',
    estimatedAttendance: 100
  }

];

const initialPromotions: Promotion[] = [
  {
    id: 'promo-1',
    title: 'CS 101 & Calculus Tutor',
    description: 'Providing comprehensive 1-on-1 tutoring sessions to nail coding labs and derivative theorems. $15/hr, student discount package available.',
    category: 'tutoring',
    status: 'approved',
    date: '2026-06-25',
    organizer: 'Sarah Jenkins',
    contactInfo: 's.jenkins@university.edu'
  },
  {
    id: 'promo-2',
    title: 'Graduation & Event Photographer',
    description: 'Capture beautiful graduation frames and club social highlights. Professional lighting and 4K digital prints delivered in 3 days.',
    category: 'photography',
    status: 'approved',
    date: '2026-06-26',
    organizer: 'David Kim',
    contactInfo: 'david.k@university.edu'
  }
];

const initialNotifications: Notification[] = [
  {
    id: 'notif-1',
    title: 'RSVP Confirmed',
    message: 'Your spot at the Homecoming Kickoff Rally is locked in! Doors open at 17:30.',
    type: 'rsvp',
    timestamp: '2 hours ago',
    read: false,
    username: 'michael_c'
  },
  {
    id: 'notif-2',
    title: 'Event Approved',
    message: 'Your event "STEM Innovation Expo" has been approved by Dean Dean and is now published.',
    type: 'approve',
    timestamp: '1 day ago',
    read: true,
    username: 'sarah_j'
  }
];

// Ensure DB initialization
function ensureDB() {
  const dir = path.dirname(DB_PATH);
  if (!fs.existsSync(dir)) {
    fs.mkdirSync(dir, { recursive: true });
  }
  if (!fs.existsSync(DB_PATH)) {
    const defaultData: DBStructure = {
      events: initialEvents,
      promotions: initialPromotions,
      organizations: initialOrganizations,
      users: initialUsers,
      notifications: initialNotifications
    };
    fs.writeFileSync(DB_PATH, JSON.stringify(defaultData, null, 2), 'utf8');
  }
}

export function readDB(): DBStructure {
  ensureDB();
  const data = fs.readFileSync(DB_PATH, 'utf8');
  return JSON.parse(data) as DBStructure;
}

export function writeDB(data: DBStructure) {
  ensureDB();
  fs.writeFileSync(DB_PATH, JSON.stringify(data, null, 2), 'utf8');
}

export function resetDB() {
  const defaultData: DBStructure = {
    events: initialEvents,
    promotions: initialPromotions,
    organizations: initialOrganizations,
    users: initialUsers,
    notifications: initialNotifications
  };
  writeDB(defaultData);
  return defaultData;
}
